### ISSUE TITLE
Error  get the codebook

### ISSUE THREAD

**Issue by ljhp** [DUT-DIPLab/Locality-Constrained-Linear-Coding#1]
Hi,When I use the code to get my codebook, the codebook size is 256(or biger). the X is 128*200000.When I run , there is Error ([~,B]=kmeans(X,256)),X must have more rows than the number of clusters. How can I solve it ?? thx~~

**Comment by CyberZHG** [comment]
X should be a N x D matrix, where N is the number of input samples and D is the dimension of  the features. Therefore you should use the transposed matrix X', which is 200000 x 128.

**Comment by ljhp** [comment]
thanks,Do as what you said ,[~, B] = kmeans(X', M);B=B'; 
there is an error too, <Empty cluster created at iteration 1.>
if I just use vl_kmeans to get the codebook to do as CVPR 2010, will the result influence?? thanks your reply again.

**Comment by CyberZHG** [comment]
I don't think __B__ should be transposed after k-means.
Generally, _empty clusters_ means you may have chosen an improper value of __k__ which makes it hard to divide the data into clusters. And sometimes you could ignore this warning.

Besides, this is just an unofficial implementation, I think you should use the codes provided by the author of the paper to make sure your experimental results are correct.
